import argparse
from automate_spotify import *


def main():
    parser = argparse.ArgumentParser("Automate Python Program")
    parser.add_argument("-u", "--user", action="store_true", help="Show user's information.")
    parser.add_argument("-p", "--playlists", action="store_true", help="Show user's playlist.")
    parser.add_argument("-t", "--tracks", type=int, nargs="?", const=10, default=10, help="Show user's saved tracks. Enter the number of tracks you want to view (default=10).")
    parser.add_argument("-w", "--weekly", action="store_true", help="Show user's this week Weekly Discovery playlist generated by Spotify.")

    args = parser.parse_args()
    if args.user:
        view_user_info()
    elif args.playlists:
        view_user_playlists()
    elif args.tracks:
        view_user_saved_tracks()
    elif args.weekly:
        view_weekly_discovery_tracks()
    else:
        print("Invalid command.")

if __name__ == "__main__":
    main()